mysite/loginsys/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'auth'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/$',views.register,name='register')
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^', include('polls.urls'))
]

mysite/polls/urls.py
from django.conf.urls import url,include

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$',views.result,name='result'),
    url(r'^(?P<question_id>[0-9]+)/votes/$',views.votes,name='votes'),
    url(r'^page/(\d+)/$', views.index)
]

mysite/loginsys/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
from django.db import models


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date publsihed')
    def __str__(self):
        return self.question_text



class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/loginsys/views.py


# Create your
#
#  views here.
from django.contrib import auth
from django.template.context_processors import csrf
from django.shortcuts import render,redirect,render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm





def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username = username,password = password )
        if user is not None:
            auth.login(request,user)
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            args['login_error'] = "bred"
            return render_to_response('loginsys/login.html',args)
    else:
            return render_to_response('loginsys/login.html',args)



def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('polls:index'))

def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm
    if request.POST:
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user = auth.authenticate(username = new_user_form.cleaned_data['username'], password = new_user_form.cleaned_data['password1'])
            auth.login(request,new_user)
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            args['form'] = new_user_form
    return render(request,"loginsys/register.html",args)

mysite/polls/views.py

from django.http import HttpResponse,HttpResponseRedirect,Http404
from .models import Question,Choice
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.core.paginator import Paginator



# Create your views here.
def index(request,page_number = 1):
    question_list = Question.objects.all()
    current_list = Paginator(question_list,4)
    return render(request,'polls/index.html',{'latest_question_list':current_list.page(page_number),'username':auth.get_user(request).username})


def detail(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not excist')
    return render(request,'polls/detail.html',{'question':question})

def result(request, question_id):
    question = get_object_or_404(Question,pk = question_id)
    return render(request,'polls/result.html',{'question':question})



def votes(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{'question': question,'error_message':'You didnt select a choise'})
    else:
        if "test" not in request.session:
            selected_choice.votes += 1
            selected_choice.save()
            request.session.set_expiry(60)
            request.session['test'] = True
        return HttpResponseRedirect('/polls/'+str(question_id)+'/results/')

mysite/loginsys/templates/loginsys/login.html
{% extends 'polls/main.html' %}
{% load staticfiles  %}

{% block login %}
    <h3 align="center">Форма авторизации</h3>
    <div class="large-offset-3 large offset-6 columns" align="center">
        <form action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}
            <label for="username">Имя</label>
            <input type="text" name="username" id="username">
            <label for="password">Пароль</label>
            <input type="password" name="password" id="password">
            {% if login_error %}
                <label class="error">{{ login_error }}</label>
            {% endif %}
            <input class="Button" type="submit" value="Entire">
        </form>
    </div>
    <br>
    <div class="label round secondary" align="center">
        <a href="{% url 'auth:register' %}"> Регистрация </a>
    </div>


{% endblock %}

mysite/loginsys/templates/loginsys/register.html
{% extends 'polls/main.html' %}

{% block register %}
    <form action="{% url 'auth:register' %}" method="post" align="center">
        {% csrf_token %}
        {{ form }}
        <br>
        <input class="button" type="submit" value="Register">
    </form>
    <br>
    <a href="{% url 'polls:index' %}" align="center">Назад</a>
{% endblock %}

mysite/polls/templates/polls/detail.html

<html>
<head>
    <title>Django</title>
</head>
<body>

<h1 align="center">{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if user %}
<form action="{% url 'polls:votes' question.id %}" method="post" align="center">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endif %}
</body>
</html>

mysite/polls/templates/polls/index.html
{% extends 'polls/main.html' %}
{% load staticfiles %}

{% block index %}
    <html>
    <head>
        <title>Django</title>
        <link href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    </head>
    <body>
    <h1 align="center"> Авторизация </h1>
    <div class="top-bar" align="center">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          {% if username %}
              <li><a href="{% url 'auth:logout' %}">Exit? ({{ username }})</a> </li>
          {% else %}
              <li><a href="{% url 'auth:login' %}">Entire? </a> </li>
                {% endif %}
        </ul>
      </div>
    </div>
    <h1 align="center">Мой блог</h1>
    <br>
    <br>
    <br>
    {% if latest_question_list %}
        <ol align="center">
        {% for question in latest_question_list %}
            <h4>{{ question.pub_date }}</h4>
            <h2><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2>
            <hr/>
            <br>
        {% endfor %}
        </ol>
    {% else %}
        <p align="center">No polls are available.</p>
    {% endif %}
    <div class="row">
        <div class="large-3 large-offset-5 columns" align="center">
            <ul class="pagination">
                {% if latest_question_list.has_previous %}
                    <li class="arrow"><a href="/polls/page/{{ latest_question_list.previous_page_number }}/">Дальше</a> </li>
                {% else %}
                    <li class="arrow unavailable"><a href="">Дальше</a> </li>
                {% endif%}
                {% for page in latest_question_list.paginator.page_range %}
                    {% if page == latest_question_list.number %}
                        <li class="current"><a href="/page/{{ page }}/">{{ page }}</a> </li>
                    {% else %}
                        <li><a href="/page/{{ page }}/">{{ page }}</a> </li>
                    {% endif %}
                {% endfor %}
                {% if latest_question_list.has_next %}
                    <li class="arrow"><a href="/polls/page/{{ latest_question_list.next_page_number }}/">Предыдущее</a> </li>
                {% else %}
                    <li class="arrow unavailable"><a href="">Предыдущее;</a> </li>
                {% endif %}

            </ul>
        </div>
    </div>
    <img src="{% static 'polls/pe.png' %}" width="100%">

{% endblock %}


</body>
</html>

mysite/polls/templates/polls/main.html
{% load staticfiles %}

<!DOCTYPE html>

<div class="row">
    {% block index %}{% endblock %}
    {% block login %}{% endblock %}
    {% block register %}{% endblock %}
</div>

mysite/polls/templates/polls/result.html
<h1>{{  question.question_text }}</h1>

<u1>
    {% for choice in question.choice_set.all %}
        <l1> {{ choice.choice_text }}--{{ choice.votes }} vote{{ choice.votes|pluralize }}<br/> </l1>
    {% endfor %}
</u1>

<a href="{% url 'polls:index'  %}">Return to list?</a>